@startuml

hide circle
skinparam monochrome true
skinparam classAttributeIconSize 0
skinparam backgroundcolor white
'skinparam groupInheritance 2
package db {
    package local {
        package DAOs {
            interface CisBdpmDao {
                + getAll(): List<CisBdpm>
                + search100(searchQuery: String): List<CisBdpm>
                + getById(CodeCIS: Int): List<CisBdpm>
                + insertAll(CisBdpmDaos: List<CisBdpm>)
                + delete(CisBdpmDao: CisBdpm)
                + update(CisBdpmDao: CisBdpm)
                + deleteAll() 
            }
            interface CisCompoBdpmDao {
                + getAll(): List<CisCompoBdpm>
                + getById(CodeCIS: Int): List<CisCompoBdpm>
                + insertAll(CisCompoBdpmDaos: List<CisCompoBdpm>)
                + delete(CisCompoBdpmDao: CisCompoBdpm)
                + update(CisCompoBdpmDao: CisCompoBdpm)
                + deleteAll() 
            }

            interface ContactDao {
                + getAll(): List<Contact>
                + getById(Rpps: Int): List<Contact>
                + getByUuid(uuid: String): List<Contact>
                + getByIdAndUuid(Rpps: Long, uuid: String): Contact
                + getByIdAndUuid(Rpps: Int, uuid: String): Contact
                + insertAll(vararg ContactDaos: Contact)
                + delete(ContactDao: Contact)
                + update(ContactDao: Contact)
                + deleteAll()
            }

            interface EffetSecondaireDao{
                + getAll(): List<EffetSecondaire>
                + getByuuidUser(uuidUser: String): List<EffetSecondaire>
                + insertAll(vararg EffetSecondaireDaos: EffetSecondaire)
                + delete(EffetSecondaireDao: EffetSecondaire)
                + update(EffetSecondaireDao: EffetSecondaire)
                + deleteAll()
            }

            interface InteractionDao{
                + getAllLike(substance: String): List<Interaction>
                + getBySubstance(substance: String): List<Interaction>
                + insertAll(vararg InteractionDaos: Interaction)
            }

            interface MedocDao {
                + getAll(): List<Medoc>
                + getById(uuid: String): List<Medoc>
                + getByUser(uuidUser: String): List<Medoc>
                + insertAll(Medoc: List<Medoc>)
                + delete(Medoc: Medoc)
                + update(Medoc: Medoc)
            }
            interface PriseValideeDao {
                + getAll(): List<PriseValidee>
                + getById(CodeCIS: Int): List<PriseValidee>
                + getByUUIDTraitementAndDate(date: String, uuidPrise: String): List<PriseValidee>
                + insertAll(priseValidee: PriseValidee)
                + delete(priseValidee: PriseValidee)
                + update(priseValidee: PriseValidee)
            }
            interface UserDao {
                + getAll(): List<User>
                + getById(CodeCIS: Int): List<User>
                + getByConnected(isConnected: Boolean = true): List<User>
                + insertAll(users: List<User>)
                + delete(User: User)
                + update(User: User)
            }

        }

        package Repositories {
            class CisBdpmRepository {
                - cisBdpmDao: CisBdpmDao
                + getAllCisBdpm(): List<CisBdpm>
                + search100(searchQuery: String): List<CisBdpm>
                + getOneCisBdpmById(CodeCIS: Int): List<CisBdpm>
                + insertCisBdpm(cisBdpm: CisBdpm): Pair<Boolean, String>
                + insertFromCsv(context: Context)
                - parseCsv(csvContent: String): List<CisBdpm>
                + deleteCisBdpm(cisBdpm: CisBdpm): Pair<Boolean, String>
                + updateCisBdpm(cisBdpm: CisBdpm): Pair<Boolean, String>
            }

            class CisCompoBdpmRepository {
                - cisCompoBdpmDao: CisCompoBdpmDao
                + getAllCisCompoBdpm(): List<CisCompoBdpm>
                + getOneCisCompoBdpmById(CodeCIS: Int): List<CisCompoBdpm>
                + insertCisCompoBdpm(cisCompoBdpm: CisCompoBdpm): Pair<Boolean, String>
                + insertFromCsv(context: Context)
                + parseCsv(csvContent: String): List<CisCompoBdpm>
                + deleteCisBdpm(cisCompoBdpm: CisCompoBdpm): Pair<Boolean, String>
                + updateCisBdpm(cisCompoBdpm: CisCompoBdpm): Pair<Boolean, String>
            }

            class CisSideInfosRepository{
                - CisSideInfosDao: CisSideInfosDao
                + getAllCisSideInfos(): List<CisSideInfos>
                + getOneCisSideInfosById(CodeCIS: Int): List<CisSideInfos>
                + insertCisSideInfos(cisSideInfos: CisSideInfos): Pair<Boolean, String>
                + insertFromCsv(context: Context)
                - parseCsv(csvContent: String): List<CisSideInfos>
                + deleteCisSideInfos(cisSideInfos: CisSideInfos): Pair<Boolean, String>
                + updateCisSideInfos(cisSideInfos: CisSideInfos): Pair<Boolean, String>
            }

            class ContactRepository {
                - ContactDao: ContactDao
                + getAllContact(): List<Contact>
                + getOneContactById(uuid: String, rpps: Long): Contact?
                + getContactsByUuid(uuid: String): List<Contact>
                + insertContact(Contact: Contact): Pair<Boolean, String>
                + deleteContact(Contact: Contact): Pair<Boolean, String>
                + updateContact(Contact: Contact): Pair<Boolean, String>
            }

            class MedocRepository {
                - medocDao: MedocDao
                + insert(medoc: Medoc)
                + selectAll(): List<Medoc>
            }
            class PriseValideeRepository {
                - priseValideeDao: PriseValideeDao
                + insert(prise: PriseValidee)
                + selectAll(): List<PriseValidee>
            }
            class UserRepository {
                - userDao: UserDao
                + getAllUsers(): List<User>
                + getOneUserById(uuid: String): List<User>
                + getUsersConnected(isConnected: Boolean = true): List<User>
                + insertUser(user: User): Pair<Boolean, String>
                + deleteUser(user: User): Pair<Boolean, String>
                + updateUser(user: User, isPasswordChanged: Boolean = false): Pair<Boolean, String>
                + hashPassword(password: String): String
                + setConnected(user: User): Pair<Boolean, String>
                + isValidPassword(pass: String): Pair<Boolean, String>
            }
            class ContactRepository{
                - contactDao: ContactDao
                + getAllContact(): List<Contact>
                + getOneContactById(uuid: String, rpps: Long): Contact?
                + getContactsByUuid(uuid: String): List<Contact>
                + insertContact(Contact: Contact): Pair<Boolean, String>
                + deleteContact(Contact: Contact): Pair<Boolean, String>
                + updateContact(Contact: Contact): Pair<Boolean, String>
            }
        }

        package Entities {
                class CisBdpm {
                - CodeCIS: Int
                - denomination: String
                - formePharmaceutique: String
                - voiesAdministration: String
                - statutAdministratifAMM: String
                - typeProcedureAMM: String
                - etatCommercialisation: String
                - dateAMM: String
                - statutBdm: String
                - numeroAutorisationEuropeenne: String
                - titulaire: String
                - surveillanceRenforcee: String
            }

            class CisCompoBdpm{
                - CodeCIS: Int
                - designationForme: String
                - codeSubstance: String
                - denomination: String
                - dosage: String
                - referenceDosage: String
                - natureComposant: String
                - numeroLiaisonSAFT: String
            }

            class Medoc{
                - uuid: String
                - uuidUser: String
                - CodeCIS: Int?
                - nom: String
                - dosageNB: String,
                - dosageUnite: Strin
                - dateFinTraitement: String?
                - typeComprime: String
                - comprimesRestants: Int?
                - expire: Boolean
                - effetsSecondaires: String?
                - prises: String?
                - TotalQuantite: Int?
                - dateDbtTraitement: String?
            }

            class PriseValidee {
                - uuid: String
                - date: String
                - uuidPrise: String
                - statut: String
            }

            class User {
                - username: String
                - password: String
                + setUsername(username: String) : void
                + setPassword(password: String) : void
                + getUsername() : String
                + getPassword() : String
            }
            class Prise {
                - numeroPrise: String
                - heurePrise: String
                - quantite: Int
                - dosageUnite: String
                + getNumeroPrise() : String
                + getHeurePrise() : String
                + getQuantite() : Int
                + getDosageUnite() : String
            }

            class Contact{
                - uuid: String
                - rpps: Long
                - firstName: String
                - lastName: String
                - fullName: String
                - specialty: String?
                - address: String?
                - zipcode: String?
                - city: String?
                - phoneNumber: String?
                - email: String?
                + fromPractician(uuid: String, practician: Practician): Contact
            }

        }

        abstract class AppDatabase {
            - userDao: UserDao
            - medocDao: MedocDao
            - cisBdpmDao: CisBdpmDao
            - priseValideeDao: PriseValideeDao
            - cisCompoBdpmDao: CisCompoBdpmDao
            + getUserDao() : UserDao
            + getMedocDao() : MedocDao
            + getCisBdpmDao() : CisBdpmDao
            + getPriseValideeDao() : PriseValideeDao
            + getCisCompoBdpmDao() : CisCompoBdpmDao
        }
    }
}

CisBdpmRepository --> CisBdpmDao : Uses
CisCompoBdpmRepository --> CisCompoBdpmDao : Uses
MedocRepository --> MedocDao : Uses
PriseValideeRepository --> PriseValideeDao : Uses
UserRepository --> UserDao : Uses

CisBdpmDao --> CisBdpm : Aggregates
CisCompoBdpmDao --> CisCompoBdpm : Aggregates
MedocDao --> Medoc : Aggregates
PriseValideeDao --> PriseValidee : Aggregates
UserDao --> User : Aggregates

AppDatabase --> UserDao : Uses
AppDatabase --> MedocDao : Uses
AppDatabase --> CisBdpmDao : Uses
AppDatabase --> PriseValideeDao : Uses
AppDatabase --> CisCompoBdpmDao : Uses

@enduml
